/** Generated from Snack Display (Allocation Plan).xlsx — sheet POSM. */
window.DISPLAY_ALLOCATION_NPP = [
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HCMC",
    "cdm": "Nguyễn Thị Thủy",
    "kam": "Châu Quí",
    "code": "NPP107",
    "name": "Hoàng Phong",
    "frameMixPlan": 20,
    "standeeMixPlan": 2,
    "allocFrameMix": 17,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 8,
    "standeeBzPlan": 2,
    "allocFrameBz": 7,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HCMC",
    "cdm": "Nguyễn Thị Thủy",
    "kam": "Nguyễn Thanh Bình",
    "code": "NPP215",
    "name": "Mai Liên Thành",
    "frameMixPlan": 10,
    "standeeMixPlan": 2,
    "allocFrameMix": 8,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 3,
    "standeeBzPlan": 2,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HCMC",
    "cdm": "Nguyễn Thị Thủy",
    "kam": "Ngô Thành Ý",
    "code": "NPP263",
    "name": "Thái Sơn",
    "frameMixPlan": 10,
    "standeeMixPlan": 15,
    "allocFrameMix": 7,
    "allocStandeeMix": 12,
    "allocHangerMix": 10,
    "frameBzPlan": 3,
    "standeeBzPlan": 2,
    "allocFrameBz": 3,
    "allocStandeeBz": 1,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HCMC",
    "cdm": "Nguyễn Thị Thủy",
    "kam": "Nguyễn Minh Tâm",
    "code": "NPP296",
    "name": "Vạn Thành Công",
    "frameMixPlan": 10,
    "standeeMixPlan": 5,
    "allocFrameMix": 4,
    "allocStandeeMix": 2,
    "allocHangerMix": 10,
    "frameBzPlan": 3,
    "standeeBzPlan": 2,
    "allocFrameBz": 3,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HCMC",
    "cdm": "Nguyễn Thị Thủy",
    "kam": "Nguyễn Minh Tâm",
    "code": "NPP309",
    "name": "68 Food",
    "frameMixPlan": 0,
    "standeeMixPlan": 9,
    "allocFrameMix": 0,
    "allocStandeeMix": 7,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 2,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "south",
    "label": "HCMC",
    "area": "HCMC",
    "frameMixPlan": 50,
    "standeeMixPlan": 33,
    "allocFrameMix": 36,
    "allocStandeeMix": 21,
    "allocHangerMix": 30,
    "frameBzPlan": 19,
    "standeeBzPlan": 10,
    "allocFrameBz": 13,
    "allocStandeeBz": 1,
    "allocHangerBz": 50
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Huỳnh Văn Giàu",
    "code": "NPP10",
    "name": "Diệp Tuyết Mai",
    "frameMixPlan": 8,
    "standeeMixPlan": 1,
    "allocFrameMix": 1,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Phạm Trần Quang",
    "code": "NPP297",
    "name": "Nhi Tường",
    "frameMixPlan": 6,
    "standeeMixPlan": 1,
    "allocFrameMix": 1,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 2,
    "allocFrameBz": 2,
    "allocStandeeBz": 2,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Trương Hào Hiệp",
    "code": "NPP268",
    "name": "Trần Mỹ Kim",
    "frameMixPlan": 0,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 0,
    "standeeBzPlan": 0,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 0
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Nguyễn Hải Âu",
    "code": null,
    "name": "Phương Nghi",
    "frameMixPlan": 4,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Lê Thanh Tiến",
    "code": null,
    "name": "Thuận Thiên",
    "frameMixPlan": 4,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "NMK",
    "cdm": "Phạm Thị Anh Thư",
    "kam": "Phạm Trần Quang",
    "code": "NPP282",
    "name": "Văn Mai Hưng",
    "frameMixPlan": 8,
    "standeeMixPlan": 2,
    "allocFrameMix": 4,
    "allocStandeeMix": 1,
    "allocHangerMix": 10,
    "frameBzPlan": 3,
    "standeeBzPlan": 1,
    "allocFrameBz": 3,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "south",
    "label": "NMK",
    "area": "NMK",
    "frameMixPlan": 30,
    "standeeMixPlan": 5,
    "allocFrameMix": 6,
    "allocStandeeMix": 1,
    "allocHangerMix": 50,
    "frameBzPlan": 11,
    "standeeBzPlan": 6,
    "allocFrameBz": 5,
    "allocStandeeBz": 2,
    "allocHangerBz": 50
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Nguyễn Hong Kong",
    "code": "NPP312",
    "name": "Khang Gia Phát",
    "frameMixPlan": 8,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 2,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Phan Hồ Thanh Trúc",
    "code": "NPP302",
    "name": "Kim Loan",
    "frameMixPlan": 5,
    "standeeMixPlan": 1,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Trần Thanh Nhã",
    "code": "NPP262",
    "name": "Ngọc San",
    "frameMixPlan": 8,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 3,
    "allocHangerMix": 10,
    "frameBzPlan": 3,
    "standeeBzPlan": 1,
    "allocFrameBz": 3,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Phan Hồ Thanh Trúc",
    "code": "NPP311",
    "name": "Nguyễn Hồ",
    "frameMixPlan": 4,
    "standeeMixPlan": 0,
    "allocFrameMix": 1,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Nguyễn Trung Hiếu",
    "code": "NPP246",
    "name": "Nhi Phước Thành",
    "frameMixPlan": 8,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Phạm Chiến Thắng",
    "code": "NPP307",
    "name": "Thiện Vân Minh Phát",
    "frameMixPlan": 12,
    "standeeMixPlan": 1,
    "allocFrameMix": 12,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 20,
    "allocFrameBz": 1,
    "allocStandeeBz": 20,
    "allocHangerBz": 5
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Nguyễn Hong Kong",
    "code": "NPP284",
    "name": "Thành Tiến Đạt",
    "frameMixPlan": 0,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 0,
    "standeeBzPlan": 0,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 0
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Phan Hồ Thanh Trúc",
    "code": "NPP269",
    "name": "Thiên Ân",
    "frameMixPlan": 0,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 0,
    "standeeBzPlan": 0,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 0
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "SMK",
    "cdm": "Hoàng Anh Tú",
    "kam": "Phạm Chiến Thắng",
    "code": "KEYSMK03",
    "name": "Tư Muỗi",
    "frameMixPlan": 8,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 9,
    "allocFrameBz": 0,
    "allocStandeeBz": 9,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "south",
    "label": "SMK",
    "area": "SMK",
    "frameMixPlan": 53,
    "standeeMixPlan": 4,
    "allocFrameMix": 15,
    "allocStandeeMix": 3,
    "allocHangerMix": 70,
    "frameBzPlan": 15,
    "standeeBzPlan": 34,
    "allocFrameBz": 6,
    "allocStandeeBz": 29,
    "allocHangerBz": 65
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Eastern",
    "cdm": "Lê Trần Kim Khánh",
    "kam": "Lý Đỗ Phương",
    "code": "NPP5",
    "name": "Bạch Mai",
    "frameMixPlan": 10,
    "standeeMixPlan": 10,
    "allocFrameMix": 8,
    "allocStandeeMix": 3,
    "allocHangerMix": 0,
    "frameBzPlan": 2,
    "standeeBzPlan": 9,
    "allocFrameBz": 0,
    "allocStandeeBz": 7,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Eastern",
    "cdm": "Lê Trần Kim Khánh",
    "kam": "Bùi Thị Thanh Thủy",
    "code": "NPP228",
    "name": "Đồng Thuận",
    "frameMixPlan": 10,
    "standeeMixPlan": 8,
    "allocFrameMix": 2,
    "allocStandeeMix": 2,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Eastern",
    "cdm": "Lê Trần Kim Khánh",
    "kam": "Võ Thị Thanh Trà",
    "code": "NPP255",
    "name": "Hoàng Anh Khoa",
    "frameMixPlan": 23,
    "standeeMixPlan": 0,
    "allocFrameMix": 1,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 4,
    "standeeBzPlan": 2,
    "allocFrameBz": 4,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Eastern",
    "cdm": "Lê Trần Kim Khánh",
    "kam": "Phạm Hữu Hạnh",
    "code": "NPP292",
    "name": "Quân Lộc Phát",
    "frameMixPlan": 18,
    "standeeMixPlan": 2,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 2,
    "standeeBzPlan": 2,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Eastern",
    "cdm": "Lê Trần Kim Khánh",
    "kam": "Phạm Hữu Hạnh",
    "code": "NPP7",
    "name": "Song Nhiên",
    "frameMixPlan": 4,
    "standeeMixPlan": 0,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 0,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 1,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "south",
    "label": "Eastern",
    "area": "Eastern",
    "frameMixPlan": 65,
    "standeeMixPlan": 20,
    "allocFrameMix": 13,
    "allocStandeeMix": 5,
    "allocHangerMix": 20,
    "frameBzPlan": 12,
    "standeeBzPlan": 15,
    "allocFrameBz": 5,
    "allocStandeeBz": 7,
    "allocHangerBz": 50
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Central",
    "cdm": "Vũ Ngọc Hải",
    "kam": "Bùi Công Phước",
    "code": "NPP196",
    "name": "Thái Đông Hưng",
    "frameMixPlan": 30,
    "standeeMixPlan": 5,
    "allocFrameMix": 15,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 4,
    "standeeBzPlan": 3,
    "allocFrameBz": 1,
    "allocStandeeBz": 0,
    "allocHangerBz": 15
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "Central",
    "cdm": "Vũ Ngọc Hải",
    "kam": "Hồ Văn Tiến",
    "code": null,
    "name": "Phát Phước Đức",
    "frameMixPlan": 4,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 5,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 5
  },
  {
    "kind": "npp",
    "region": "south",
    "hq": "South",
    "area": "HLEC",
    "cdm": "Vũ Ngọc Hải",
    "kam": "Vũ Ngọc Hải",
    "code": null,
    "name": "Minh Toàn",
    "frameMixPlan": 10,
    "standeeMixPlan": 3,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "south",
    "label": "Central + HL",
    "area": "Central + HL",
    "frameMixPlan": 44,
    "standeeMixPlan": 8,
    "allocFrameMix": 15,
    "allocStandeeMix": 0,
    "allocHangerMix": 25,
    "frameBzPlan": 8,
    "standeeBzPlan": 5,
    "allocFrameBz": 1,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "kind": "regionTotal",
    "region": "south",
    "label": "South",
    "frameMixPlan": 242,
    "standeeMixPlan": 70,
    "allocFrameMix": 85,
    "allocStandeeMix": 30,
    "allocHangerMix": 195,
    "frameBzPlan": 65,
    "standeeBzPlan": 70,
    "allocFrameBz": 30,
    "allocStandeeBz": 39,
    "allocHangerBz": 245
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "Hanoi",
    "cdm": "Phạm Quốc Toản",
    "kam": "Vũ Tuyết Hiền",
    "code": "NPP247",
    "name": "Hải Đạt",
    "frameMixPlan": 21,
    "standeeMixPlan": 7,
    "allocFrameMix": 11,
    "allocStandeeMix": 5,
    "allocHangerMix": 10,
    "frameBzPlan": 12,
    "standeeBzPlan": 2,
    "allocFrameBz": 4,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "Hanoi",
    "cdm": "Phạm Quốc Toản",
    "kam": "Vũ Tuyết Hiền",
    "code": "NPP306",
    "name": "Mai Linh",
    "frameMixPlan": 10,
    "standeeMixPlan": 2,
    "allocFrameMix": 4,
    "allocStandeeMix": 2,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 1,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "Hanoi",
    "cdm": "Phạm Quốc Toản",
    "kam": "Phạm Văn Quân",
    "code": "NPP227",
    "name": "Trường Minh",
    "frameMixPlan": 15,
    "standeeMixPlan": 3,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 5,
    "standeeBzPlan": 1,
    "allocFrameBz": 5,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "north",
    "label": "Hanoi",
    "area": "Hanoi",
    "frameMixPlan": 46,
    "standeeMixPlan": 12,
    "allocFrameMix": 17,
    "allocStandeeMix": 7,
    "allocHangerMix": 30,
    "frameBzPlan": 19,
    "standeeBzPlan": 4,
    "allocFrameBz": 10,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "North West",
    "cdm": "Phạm Quốc Toản",
    "kam": "Nguyễn Ngọc Long",
    "code": "NPP240",
    "name": "Huyền Hảo",
    "frameMixPlan": 23,
    "standeeMixPlan": 2,
    "allocFrameMix": 23,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 27,
    "standeeBzPlan": 2,
    "allocFrameBz": 27,
    "allocStandeeBz": 1,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "north",
    "label": "North West",
    "area": "North West",
    "frameMixPlan": 23,
    "standeeMixPlan": 2,
    "allocFrameMix": 23,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 27,
    "standeeBzPlan": 2,
    "allocFrameBz": 27,
    "allocStandeeBz": 1,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "North Coast",
    "cdm": "Phạm Quốc Toản",
    "kam": "Nguyễn Thanh Quỳnh",
    "code": "NPP285",
    "name": "Thanh Lê",
    "frameMixPlan": 5,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 6,
    "standeeBzPlan": 1,
    "allocFrameBz": 6,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "north",
    "label": "North Coast",
    "area": "North Coast",
    "frameMixPlan": 5,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 6,
    "standeeBzPlan": 1,
    "allocFrameBz": 6,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "North East",
    "cdm": "Vacant",
    "kam": "Nguyễn Đình Thái (HP)",
    "code": "NPP310",
    "name": "Phong Quyên",
    "frameMixPlan": 5,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 2,
    "standeeBzPlan": 1,
    "allocFrameBz": 0,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "North East",
    "cdm": "Vacant",
    "kam": "Nguyễn Đình Thái (HP)",
    "code": "NPP206",
    "name": "Thảo Nguyên Vina",
    "frameMixPlan": 31,
    "standeeMixPlan": 0,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 13,
    "standeeBzPlan": 1,
    "allocFrameBz": 10,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "npp",
    "region": "north",
    "hq": "North",
    "area": "North East",
    "cdm": "Vacant",
    "kam": "Nguyễn Đình Thái (HP)",
    "code": "NPP283",
    "name": "Uyên Cường",
    "frameMixPlan": 18,
    "standeeMixPlan": 0,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 8,
    "standeeBzPlan": 1,
    "allocFrameBz": 4,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "kind": "areaTotal",
    "region": "north",
    "label": "North East",
    "area": "North East",
    "frameMixPlan": 54,
    "standeeMixPlan": 0,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 30,
    "frameBzPlan": 23,
    "standeeBzPlan": 3,
    "allocFrameBz": 14,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "kind": "regionTotal",
    "region": "north",
    "label": "North",
    "frameMixPlan": 128,
    "standeeMixPlan": 15,
    "allocFrameMix": 42,
    "allocStandeeMix": 7,
    "allocHangerMix": 80,
    "frameBzPlan": 75,
    "standeeBzPlan": 10,
    "allocFrameBz": 57,
    "allocStandeeBz": 1,
    "allocHangerBz": 80
  },
  {
    "kind": "national",
    "region": "all",
    "label": "National",
    "frameMixPlan": 370,
    "standeeMixPlan": 85,
    "allocFrameMix": 127,
    "allocStandeeMix": 37,
    "allocHangerMix": 275,
    "frameBzPlan": 140,
    "standeeBzPlan": 80,
    "allocFrameBz": 87,
    "allocStandeeBz": 40,
    "allocHangerBz": 325
  }
];

window.DISPLAY_ALLOCATION = [
  {
    "label": "HCMC",
    "region": "south",
    "frameMixPlan": 50,
    "standeeMixPlan": 33,
    "allocFrameMix": 36,
    "allocStandeeMix": 21,
    "allocHangerMix": 30,
    "frameBzPlan": 19,
    "standeeBzPlan": 10,
    "allocFrameBz": 13,
    "allocStandeeBz": 1,
    "allocHangerBz": 50
  },
  {
    "label": "NMK",
    "region": "south",
    "frameMixPlan": 30,
    "standeeMixPlan": 5,
    "allocFrameMix": 6,
    "allocStandeeMix": 1,
    "allocHangerMix": 50,
    "frameBzPlan": 11,
    "standeeBzPlan": 6,
    "allocFrameBz": 5,
    "allocStandeeBz": 2,
    "allocHangerBz": 50
  },
  {
    "label": "SMK",
    "region": "south",
    "frameMixPlan": 53,
    "standeeMixPlan": 4,
    "allocFrameMix": 15,
    "allocStandeeMix": 3,
    "allocHangerMix": 70,
    "frameBzPlan": 15,
    "standeeBzPlan": 34,
    "allocFrameBz": 6,
    "allocStandeeBz": 29,
    "allocHangerBz": 65
  },
  {
    "label": "Eastern",
    "region": "south",
    "frameMixPlan": 65,
    "standeeMixPlan": 20,
    "allocFrameMix": 13,
    "allocStandeeMix": 5,
    "allocHangerMix": 20,
    "frameBzPlan": 12,
    "standeeBzPlan": 15,
    "allocFrameBz": 5,
    "allocStandeeBz": 7,
    "allocHangerBz": 50
  },
  {
    "label": "Central + HL",
    "region": "south",
    "frameMixPlan": 44,
    "standeeMixPlan": 8,
    "allocFrameMix": 15,
    "allocStandeeMix": 0,
    "allocHangerMix": 25,
    "frameBzPlan": 8,
    "standeeBzPlan": 5,
    "allocFrameBz": 1,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "label": "TOTAL South",
    "region": "south",
    "frameMixPlan": 242,
    "standeeMixPlan": 70,
    "allocFrameMix": 85,
    "allocStandeeMix": 30,
    "allocHangerMix": 195,
    "frameBzPlan": 65,
    "standeeBzPlan": 70,
    "allocFrameBz": 30,
    "allocStandeeBz": 39,
    "allocHangerBz": 245
  },
  {
    "label": "Hanoi",
    "region": "north",
    "frameMixPlan": 46,
    "standeeMixPlan": 12,
    "allocFrameMix": 17,
    "allocStandeeMix": 7,
    "allocHangerMix": 30,
    "frameBzPlan": 19,
    "standeeBzPlan": 4,
    "allocFrameBz": 10,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "label": "North West",
    "region": "north",
    "frameMixPlan": 23,
    "standeeMixPlan": 2,
    "allocFrameMix": 23,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 27,
    "standeeBzPlan": 2,
    "allocFrameBz": 27,
    "allocStandeeBz": 1,
    "allocHangerBz": 10
  },
  {
    "label": "North Coast",
    "region": "north",
    "frameMixPlan": 5,
    "standeeMixPlan": 1,
    "allocFrameMix": 0,
    "allocStandeeMix": 0,
    "allocHangerMix": 10,
    "frameBzPlan": 6,
    "standeeBzPlan": 1,
    "allocFrameBz": 6,
    "allocStandeeBz": 0,
    "allocHangerBz": 10
  },
  {
    "label": "North East",
    "region": "north",
    "frameMixPlan": 54,
    "standeeMixPlan": 0,
    "allocFrameMix": 2,
    "allocStandeeMix": 0,
    "allocHangerMix": 30,
    "frameBzPlan": 23,
    "standeeBzPlan": 3,
    "allocFrameBz": 14,
    "allocStandeeBz": 0,
    "allocHangerBz": 30
  },
  {
    "label": "TOTAL North",
    "region": "north",
    "frameMixPlan": 128,
    "standeeMixPlan": 15,
    "allocFrameMix": 42,
    "allocStandeeMix": 7,
    "allocHangerMix": 80,
    "frameBzPlan": 75,
    "standeeBzPlan": 10,
    "allocFrameBz": 57,
    "allocStandeeBz": 1,
    "allocHangerBz": 80
  },
  {
    "label": "National",
    "region": "all",
    "frameMixPlan": 370,
    "standeeMixPlan": 85,
    "allocFrameMix": 127,
    "allocStandeeMix": 37,
    "allocHangerMix": 275,
    "frameBzPlan": 140,
    "standeeBzPlan": 80,
    "allocFrameBz": 87,
    "allocStandeeBz": 40,
    "allocHangerBz": 325
  }
];
